# Generated by Django 5.2.1 on 2025-05-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_profile',
            fields=[
                ('empid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('name', models.CharField(max_length=255)),
                ('mobileno', models.BigIntegerField()),
                ('whatsapp', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emergency_no', models.BigIntegerField()),
                ('date_of_joining', models.CharField(max_length=100)),
                ('date_of_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('call_center', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('document_rights', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_from', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.CharField(blank=True, max_length=100, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('validity', models.DateField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10)),
            ],
            options={
                'verbose_name': 'Employee KYC Document',
                'verbose_name_plural': 'Employee KYC Documents',
                'ordering': ['issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Bank_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('IFSC', models.CharField(blank=True, max_length=11, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='bank_proof_images/')),
                ('epfo_no', models.CharField(blank=True, max_length=20, null=True)),
                ('epfo_state', models.CharField(blank=True, max_length=255, null=True)),
                ('epfo_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_no', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_state', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_add', models.TextField(blank=True, null=True)),
                ('present_country', models.CharField(blank=True, max_length=255, null=True)),
                ('present_state', models.CharField(blank=True, max_length=255, null=True)),
                ('present_city', models.CharField(blank=True, max_length=255, null=True)),
                ('present_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_add', models.TextField(blank=True, null=True)),
                ('permanent_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_country', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.company_profile')),
            ],
        ),
    ]
