# Generated by Django 5.2.3 on 2025-07-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_profile',
            fields=[
                ('empid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileno', models.BigIntegerField(blank=True, null=True)),
                ('whatsapp', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adhaar', models.BigIntegerField(blank=True, null=True)),
                ('PAN', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_salary', models.BigIntegerField(blank=True, null=True)),
                ('date_of_joining', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_loan_amount', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('salary_per_month', models.BigIntegerField(blank=True, null=True)),
                ('loan_amount', models.BigIntegerField(blank=True, null=True)),
                ('previous_loan', models.BigIntegerField(default=0)),
                ('total_loan', models.BigIntegerField(blank=True, null=True)),
                ('balance', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_details', to='Employee_Management.employee_profile')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='loan_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_documents', to='Employee_Management.employee_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(blank=True, max_length=100, null=True)),
                ('present_days', models.IntegerField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_made', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_taken', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Employee_Management.employee_profile')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='salary_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_documents', to='Employee_Management.employee_profile')),
            ],
        ),
    ]
