# Generated by Django 5.2.1 on 2025-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='emergency_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='mobileno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
