# Generated by Django 5.2.3 on 2025-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
