# Generated by Django 5.2.3 on 2025-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0002_alter_company_profile_date_of_joining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_profile',
            fields=[
                ('empid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileno', models.BigIntegerField(blank=True, null=True)),
                ('whatsapp', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adhaar', models.BigIntegerField(blank=True, null=True)),
                ('PAN', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_salary', models.BigIntegerField(blank=True, null=True)),
                ('date_of_joining', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_leaving', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='bank_others',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='Document_master',
        ),
        migrations.DeleteModel(
            name='EmployeeKYC',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Bank_Others',
        ),
        migrations.DeleteModel(
            name='Company_profile',
        ),
    ]
