# Generated by Django 5.2.3 on 2025-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0002_alter_salary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
