# Generated by Django 5.2.3 on 2025-07-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0004_loandetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='loan_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='salary_per_month',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='total_loan',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
