# Generated by Django 5.2.3 on 2025-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0006_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
