# Generated by Django 5.2.3 on 2025-07-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0009_loandocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandocument',
            name='loan',
        ),
    ]
