# Generated by Django 5.2.1 on 2025-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0010_remove_loandocument_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10, null=True),
        ),
    ]
