# Generated by Django 5.2.3 on 2025-07-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0013_salary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
