# Generated by Django 5.2.3 on 2025-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0014_alter_employee_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
