# Generated by Django 5.2.3 on 2025-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0015_alter_employee_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='updated_bal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
