# Generated by Django 5.2.3 on 2025-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0016_loandetails_updated_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='total_loan',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
