# Generated by Django 5.2.3 on 2025-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0017_alter_loandetails_total_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'PAID'), ('partial', 'PARTIAL'), ('unpaid', 'UNPAID')], default='unpaid', max_length=10, null=True),
        ),
    ]
