# Generated by Django 5.2.3 on 2025-07-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0018_alter_salary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
