# Generated by Django 5.2.1 on 2025-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_user_license_expiry_user_license_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_license_valid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
