# Generated by Django 5.2.1 on 2025-06-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_user_is_license_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_license_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
