# Generated by Django 5.2.3 on 2025-07-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_user_is_license_valid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
