# Generated by Django 5.2.1 on 2025-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('IFSC', models.CharField(blank=True, max_length=11, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_logo', models.ImageField(blank=True, null=True, upload_to='bank_logos/')),
                ('account_type', models.CharField(blank=True, choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Fixed Deposit', 'Fixed Deposit'), ('Recurring Deposit', 'Recurring Deposit'), ('NRO', 'NRO'), ('NRE', 'NRE'), ('FCNR', 'FCNR')], max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
