# Generated by Django 5.2.3 on 2025-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0002_system_bank_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System_bank_details',
        ),
        migrations.RemoveField(
            model_name='system_contact_detail',
            name='company_id',
        ),
        migrations.RenameField(
            model_name='system_company_detail',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='system_company_detail',
            old_name='registered_office_details',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='system_company_detail',
            old_name='PAN',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='system_company_detail',
            old_name='company_size',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='system_company_detail',
            old_name='country',
            new_name='contact_person_name',
        ),
        migrations.RenameField(
            model_name='system_company_detail',
            old_name='incorporation_no',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='incorporation_certificate',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='incorporation_date',
        ),
        migrations.AddField(
            model_name='system_company_detail',
            name='authorized_seak',
            field=models.ImageField(blank=True, null=True, upload_to='authorized_seak/'),
        ),
        migrations.AddField(
            model_name='system_company_detail',
            name='authorized_sign',
            field=models.ImageField(blank=True, null=True, upload_to='authorized_sign/'),
        ),
        migrations.AddField(
            model_name='system_company_detail',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logos/'),
        ),
        migrations.AddField(
            model_name='system_company_detail',
            name='designation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='system_company_detail',
            name='service',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='System_brand_detail',
        ),
        migrations.DeleteModel(
            name='System_contact_detail',
        ),
    ]
