# Generated by Django 5.2.3 on 2025-07-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0003_delete_system_bank_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_company_detail',
            name='TAX_certificate',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='authorized_seak',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='authorized_sign',
        ),
        migrations.RemoveField(
            model_name='system_company_detail',
            name='whatsappno',
        ),
    ]
